server:
  port: 8088
  max-http-header-size: 16KB

spring:
  profiles:
    active: dev
  application:
    name: spring-test-demos
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
    date-format: yyyy-MM-dd HH:mm:ss

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true